// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgclixrrlurvctnrxixq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnY2xpeHJybHVydmN0bnJ4aXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzM2ODksImV4cCI6MjA3MTk0OTY4OX0.EnGfQXfPwUs1NBYvNagPqkfMQ_BI7H4E5lho-Qbhzjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});